# Generated by Django 3.1.5 on 2021-07-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=36)),
                ('surname', models.TextField(max_length=36)),
                ('login', models.CharField(max_length=36)),
                ('password', models.CharField(max_length=8)),
                ('telephone', models.CharField(max_length=36)),
                ('picture', models.CharField(max_length=36)),
                ('mail', models.CharField(max_length=36)),
                ('address', models.CharField(max_length=36)),
                ('country', models.CharField(max_length=36)),
            ],
        ),
    ]
