# Generated by Django 3.2.5 on 2021-07-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_user_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lemodele',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col', models.CharField(max_length=36)),
            ],
        ),
    ]
