# Generated by Django 3.2.5 on 2021-07-25 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_register_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='client',
        ),
    ]
