# Generated by Django 3.2.5 on 2021-07-25 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_client_auth_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='auth_user',
            new_name='UserT',
        ),
    ]
